version: '3.8'

services:
  digital-twin-generator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./selfies:/app/selfies
      - ./models:/app/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 